# Definición de los mensajes de la acción
# Goal: 
string nombreArchivo
string texto
uint32 funcion
---
# Result: tiempo que ha pasado y cuantas actualizaciones se han dado
duration time_elapsed
uint32 updates_sent
---
# Feedback: tiempo pasado y tiempo que queda
duration time_elapsed
duration time_remaining